#!/bin/bash
cat rean_press_40_65S | sed '/[0-9]E/d; /[0-9]W/d' | tr '/' ',' | tr ':' ','  | sed 's/ 0[0-1] //g' >  rean_press_40_65S.txt

cat rean_wspd | sed '/[0-9]E/d; /[0-9]W/d' | tr '/' ',' | tr ':' ','  | sed 's/ 0[0-1] //g' >  rean_wspd.txt

cat rean_uspd | sed '/[0-9]E/d; /[0-9]W/d' | tr '/' ',' | tr ':' ','  | sed 's/ 0[0-1] //g' >  rean_uspd.txt
#less rean_uspd.txt

cat rean_uloc | sed '/[0-9]E/d; /[0-9]W/d' | tr '/' ',' | tr ':' ','  | sed 's/ 0[0-1] //g' >  rean_uloc.txt
#less rean_uloc.txt

cat rean_uwidth | sed '/[0-9]E/d; /[0-9]W/d' | tr '/' ',' | tr ':' ','  | sed 's/ 0[0-1] //g' >  rean_uwidth.txt
less rean_uwidth.txt